-- =========================
-- RICH BIZNESS — MUSIC / RADIO SAFE PATCH
-- sql/060_music.sql
-- =========================

-- MUSIC TRACKS
alter table music_tracks add column if not exists user_id uuid;
alter table music_tracks add column if not exists user_email text;
alter table music_tracks add column if not exists title text;
alter table music_tracks add column if not exists artist_name text;
alter table music_tracks add column if not exists genre text;
alter table music_tracks add column if not exists cover_url text;
alter table music_tracks add column if not exists audio_url text;
alter table music_tracks add column if not exists description text;
alter table music_tracks add column if not exists likes int default 0;
alter table music_tracks add column if not exists plays int default 0;
alter table music_tracks add column if not exists reposts int default 0;
alter table music_tracks add column if not exists created_at timestamptz default now();

alter table music_tracks enable row level security;

-- MUSIC STREAMS
alter table music_streams add column if not exists track_id bigint;
alter table music_streams add column if not exists listener_id uuid;
alter table music_streams add column if not exists artist_user_id uuid;
alter table music_streams add column if not exists played_seconds int default 0;
alter table music_streams add column if not exists is_paid_stream boolean default false;
alter table music_streams add column if not exists created_at timestamptz default now();

alter table music_streams enable row level security;

-- MUSIC EARNINGS
alter table music_earnings add column if not exists artist_user_id uuid;
alter table music_earnings add column if not exists track_id bigint;
alter table music_earnings add column if not exists source_type text default 'stream';
alter table music_earnings add column if not exists source_id bigint;
alter table music_earnings add column if not exists gross_cents int default 0;
alter table music_earnings add column if not exists note text;
alter table music_earnings add column if not exists created_at timestamptz default now();

alter table music_earnings enable row level security;

-- PREMIUM TRACK PURCHASES
alter table premium_track_purchases add column if not exists buyer_user_id uuid;
alter table premium_track_purchases add column if not exists artist_user_id uuid;
alter table premium_track_purchases add column if not exists track_id bigint;
alter table premium_track_purchases add column if not exists stripe_session_id text;
alter table premium_track_purchases add column if not exists amount_cents int default 0;
alter table premium_track_purchases add column if not exists status text default 'paid';
alter table premium_track_purchases add column if not exists created_at timestamptz default now();

alter table premium_track_purchases enable row level security;

-- MUSIC UNLOCKS
alter table music_unlocks add column if not exists user_id uuid;
alter table music_unlocks add column if not exists track_slug text;
alter table music_unlocks add column if not exists album_slug text;
alter table music_unlocks add column if not exists status text default 'active';
alter table music_unlocks add column if not exists source_payment_id bigint;
alter table music_unlocks add column if not exists created_at timestamptz default now();

alter table music_unlocks enable row level security;

-- PLAYLIST TRACKS SAFE PATCH
alter table playlist_tracks add column if not exists sort_order int default 0;
alter table playlist_tracks add column if not exists created_at timestamptz default now();

alter table playlist_tracks enable row level security;

-- ALBUM TRACKS SAFE PATCH
alter table album_tracks add column if not exists album_id bigint;
alter table album_tracks add column if not exists track_id bigint;
alter table album_tracks add column if not exists track_number int;
alter table album_tracks add column if not exists created_at timestamptz default now();

alter table album_tracks enable row level security;

-- RADIO STATIONS
create table if not exists radio_stations (
  id bigint generated by default as identity primary key,
  creator_id uuid references profiles(id) on delete set null,
  slug text unique,
  title text not null default 'Rich Bizness Radio',
  description text,
  genre text,
  cover_url text,
  is_live boolean not null default false,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table radio_stations enable row level security;

-- RADIO STATION TRACKS
create table if not exists radio_station_tracks (
  id bigint generated by default as identity primary key,
  station_id bigint references radio_stations(id) on delete cascade,
  track_id bigint,
  sort_order int default 0,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table radio_station_tracks enable row level security;

-- RADIO PLAYS
create table if not exists radio_plays (
  id bigint generated by default as identity primary key,
  station_id bigint references radio_stations(id) on delete cascade,
  track_id bigint,
  listener_id uuid references profiles(id) on delete set null,
  played_seconds int default 0,
  created_at timestamptz default now()
);

alter table radio_plays enable row level security;

-- INDEXES
create index if not exists idx_music_tracks_user_id on music_tracks(user_id);
create index if not exists idx_music_tracks_created_at on music_tracks(created_at desc);
create index if not exists idx_music_streams_track_id on music_streams(track_id);
create index if not exists idx_music_streams_listener_id on music_streams(listener_id);
create index if not exists idx_music_earnings_artist_user_id on music_earnings(artist_user_id);
create index if not exists idx_premium_track_purchases_buyer_user_id on premium_track_purchases(buyer_user_id);
create index if not exists idx_premium_track_purchases_artist_user_id on premium_track_purchases(artist_user_id);
create index if not exists idx_radio_stations_creator_id on radio_stations(creator_id);
create index if not exists idx_radio_station_tracks_station_id on radio_station_tracks(station_id);
create index if not exists idx_radio_plays_station_id on radio_plays(station_id);

-- POLICIES
drop policy if exists "music_tracks_select_all" on music_tracks;
create policy "music_tracks_select_all"
on music_tracks for select
using (true);

drop policy if exists "music_tracks_insert_self" on music_tracks;
create policy "music_tracks_insert_self"
on music_tracks for insert
with check (user_id = auth.uid());

drop policy if exists "music_tracks_update_self" on music_tracks;
create policy "music_tracks_update_self"
on music_tracks for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "music_streams_insert_any" on music_streams;
create policy "music_streams_insert_any"
on music_streams for insert
with check (true);

drop policy if exists "music_earnings_select_self" on music_earnings;
create policy "music_earnings_select_self"
on music_earnings for select
using (artist_user_id = auth.uid());

drop policy if exists "premium_track_purchases_select_related" on premium_track_purchases;
create policy "premium_track_purchases_select_related"
on premium_track_purchases for select
using (buyer_user_id = auth.uid() or artist_user_id = auth.uid());

drop policy if exists "music_unlocks_select_self" on music_unlocks;
create policy "music_unlocks_select_self"
on music_unlocks for select
using (user_id = auth.uid());

drop policy if exists "radio_stations_select_active" on radio_stations;
create policy "radio_stations_select_active"
on radio_stations for select
using (is_active = true or creator_id = auth.uid());

drop policy if exists "radio_stations_insert_self" on radio_stations;
create policy "radio_stations_insert_self"
on radio_stations for insert
with check (creator_id = auth.uid());

drop policy if exists "radio_stations_update_self" on radio_stations;
create policy "radio_stations_update_self"
on radio_stations for update
using (creator_id = auth.uid())
with check (creator_id = auth.uid());

drop policy if exists "radio_station_tracks_select_all" on radio_station_tracks;
create policy "radio_station_tracks_select_all"
on radio_station_tracks for select
using (true);

drop policy if exists "radio_plays_insert_any" on radio_plays;
create policy "radio_plays_insert_any"
on radio_plays for insert
with check (true);

NOTIFY pgrst, 'reload schema';
